### ISSUE TITLE
Split setting for your experimental reimplementation

### ISSUE THREAD

**Issue by sheunbaek** [theislab/chemCPA#148]
Hi, thanks for sharing this greatful study!

I'm trying to re-implement your code, and it looks like you're going to do nine split settings.
`'split_ho_pathway', 'split_tyrosine_ood', 'split_epigenetic_ood', 'split_cellcycle_ood', 'split_ood_finetuning', 'split_ho_epigenetic', 'split_ho_epigenetic_all', 'split_random', 'split_ood_multi_task'`

but I have a question about this part.

1. In your repo, "split_ood_multi_task" is written in several files including "manual_run.yaml" But I can't find that how to do this split setting. Can you tell me?

2. Also, can you tell me what the split setting you did in Table 1 is on the code?

Please let me know if my question is weird or if you have any additional comments.
Thank you very much in advance.

**Comment by MxMstrmn** [comment]
Hi @sheunbaek, 

you can see how the splits were created in [`preprocessing/5_sciplex_ood_splits.ipynb`](https://github.com/theislab/chemCPA/blob/7c82b787db98ec706bb32c41ad97381a256f70ff/preprocessing/5_sciplex_ood_splits.ipynb). In particular these lines of code are relevant: 
```python
# train
adata_sciplex.obs['split_ood_finetuning'] = 'train'

# ood
adata_sciplex.obs.loc[adata_sciplex.obs.condition.isin(ood_drugs), 'split_ood_finetuning'] = 'ood'

# test
validation_cond = (adata_sciplex.obs.condition.isin(validation_drugs)) & (adata_sciplex.obs.dose.isin([1e3, 1e4]))
val_idx = sc.pp.subsample(adata_sciplex[validation_cond], 0.4, copy=True, random_state=42).obs.index
adata_sciplex.obs.loc[val_idx, 'split_ood_finetuning'] = 'test'

validation_cond = (adata_sciplex.obs.condition.isin(validation_drugs)) & (adata_sciplex.obs.dose.isin([1e1, 1e2]))
val_idx = sc.pp.subsample(adata_sciplex[validation_cond], 0.2, copy=True, random_state=42).obs.index
adata_sciplex.obs.loc[val_idx, 'split_ood_finetuning'] = 'test'

validation_cond = (adata_sciplex.obs.split_ood_finetuning == 'train')
val_idx = sc.pp.subsample(adata_sciplex[validation_cond], 0.04, copy=True, random_state=42).obs.index
adata_sciplex.obs.loc[val_idx, 'split_ood_finetuning'] = 'test'

validation_cond = (adata_sciplex.obs.split_ood_finetuning == 'train') & (adata_sciplex.obs.control.isin([1]))
val_idx = sc.pp.subsample(adata_sciplex[validation_cond], 0.05, copy=True, random_state=42).obs.index
adata_sciplex.obs.loc[val_idx, 'split_ood_finetuning'] = 'test'
```

The `split_ood_multitask` is very similar to this split, only that I chose different drugs for the ood splits. This is mainly due to the signal observed in the original data, as can be checked in the supplements of the original sciplex publication. 
Specifically, I added the drugs `["Alvespimycin", "Belinostat", "Flavopiridol", "Quisinostat", "TAK-901"]` as `ood` and added the drugs `["CUDC-101", "CUDC-907", "Pirarubicin", "Raltitrexed", "Trametinib"]` to the `train` and `test` (→ val) sets in a 2/1 ratio.

The splits for Table 1 follow from this notebook: [preprocessing/6_baseline_sciplex_dataset.ipynb](https://github.com/theislab/chemCPA/blob/7c82b787db98ec706bb32c41ad97381a256f70ff/preprocessing/6_baseline_sciplex_dataset.ipynb)
